### ISSUE TITLE
Spurious filenames created

### ISSUE THREAD

**Issue by Mr-Wulf** [minostauros/tinyfilemanager-docker#5]
When using dockerised version.
**Problem** : File duplicates are created when uploading.

options-reading.php | 9.48 KB | 15.10.20 01:12 | 0644 | root:root | 
options-reading_201015011300.php | 9.48 KB | 15.10.20 01:13 | 0644 | root:root

I found no pattern beyond numbers (Copying 545 files, 552 files created, 7 extras).
It looks like some copy artifact (I know because I used to use old browser (ancient 32 bit Linux build of chrome) and it ONLY created the funny named files and not all of them),

**Browser is:**
Vivaldi | 1.15.1147.55 (Stable channel) (32-bit)
Revision | 6f366dbb9172720708b4db54fba0e304861fbd42-
OS | Linux
JavaScript | V8 6.5.254.41

**My docker-compose file is:**
```
version: "3.7"
   tiny:
     image: tigerdockermediocore/tinyfilemanager-docker:latest
     container_name: tiny-browser
     volumes:
# I set the $root_path = '/data'; in config.php
# /usr/srv is where I want the root of the files to be.
       - /usr/srv:/data
# This way, I can have editable config.php sitting outside of the container.
# You might want to publish this neat 'hack' as I had to come up with it myself.
       - /usr/srv/config.php:/app/tinyfilemanager/config.php
     ports:
       - 8080:80
     environment:
       VIRTUAL_HOST: tiny.mydomain
       LETSENCRYPT_HOST: tiny.mydomain
     restart: always
```

Anyway, it might be sometihing easy since you know the file artifact most likely by heart.
